"""
GDELT Planner + Report Generator

Planner: Hybrid routing with local Ollama router (qwen2.5:3b) + rule-based fast path + remote LLM tool execution.
Report Generator: Summarizes JSON data into natural language insights.

Both use LangChain ChatOpenAI for LLM integration.
"""

import os
import json
import re
import asyncio
from datetime import datetime, timedelta

from typing import List, Dict, Any, Optional

import httpx
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI

from backend.queries.query_utils import DEFAULT_DATA_START, DEFAULT_DATA_END


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

class QueryStep(BaseModel):
    """A single data query step in the execution plan."""
    type: str = Field(..., description="Query type: dashboard, timeseries, geo, events, overview, top_events, hot_events, daily_brief, news_context, event_detail")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the query")


class QueryContext(BaseModel):
    """Structured context extracted from natural language by the local router."""
    user_input: Optional[str] = Field(None, description="Original user query")
    location: Optional[str] = Field(None, description="Canonical location name, e.g. 'Washington DC', 'New York'")
    date_start: Optional[str] = Field(None, description="Start date in YYYY-MM-DD format")
    date_end: Optional[str] = Field(None, description="End date in YYYY-MM-DD format")
    event_type: Optional[str] = Field(None, description="One of: protest, conflict, cooperation")
    query_text: Optional[str] = Field(None, description="Free text search terms")
    intent_category: str = Field("search", description="search | detail | brief | overview | hot | off_topic")
    confidence: str = Field("high", description="high | medium | low")


class QueryPlan(BaseModel):
    """Structured plan generated by the Planner."""
    intent: str = Field(..., description="Brief description of user intent")
    thinking: Optional[str] = Field(None, description="AI reasoning for tool selection")
    time_range: Optional[Dict[str, str]] = Field(None, description="Resolved date range {start, end} if applicable")
    steps: List[QueryStep] = Field(..., description="Ordered list of queries to execute")
    visualizations: List[str] = Field(..., description="Recommended visualizations: stats_cards, timeline, map, heatmap, event_table, report")
    report_prompt: Optional[str] = Field(None, description="Optional prompt for AI report generation")
    notice: Optional[str] = Field(None, description="User-facing notice about query optimization")


class ReportResult(BaseModel):
    """AI-generated report based on query results."""
    summary: str = Field(..., description="Executive summary")
    key_findings: List[str] = Field(default_factory=list, description="Bullet point key findings")


# ---------------------------------------------------------------------------
# LLM Builder (shared between Planner and Report)
# ---------------------------------------------------------------------------

def build_llm(config: Optional[Dict[str, Any]] = None) -> ChatOpenAI:
    """Initialize LLM from environment or runtime config."""
    cfg = config or {}
    provider = cfg.get("provider", os.getenv("LLM_PROVIDER", "kimi")).lower()

    configs = {
        "kimi": {
            "api_key": cfg.get("api_key", os.getenv("KIMI_CODE_API_KEY", os.getenv("MOONSHOT_API_KEY", ""))),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.moonshot.cn/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "kimi-k2-0905-preview")),
        },
        "moonshot": {
            "api_key": cfg.get("api_key", os.getenv("MOONSHOT_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.moonshot.cn/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "kimi-k2-0905-preview")),
        },
        "claude": {
            "api_key": cfg.get("api_key", os.getenv("ANTHROPIC_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.anthropic.com/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "claude-3-5-sonnet-20241022")),
        },
        "openai": {
            "api_key": cfg.get("api_key", os.getenv("OPENAI_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.openai.com/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "gpt-4o")),
        },
    }

    provider_cfg = configs.get(provider, configs["kimi"])

    if not provider_cfg["api_key"]:
        raise ValueError(f"API key not set for provider: {provider}")

    # Kimi Coding API headers
    async def _inject_claude_headers(request: httpx.Request):
        request.headers["User-Agent"] = "claude-code/1.0"
        request.headers["X-Client-Name"] = "claude-code"

    http_async_client = httpx.AsyncClient(
        event_hooks={"request": [_inject_claude_headers]}
    )

    return ChatOpenAI(
        api_key=provider_cfg["api_key"],
        base_url=provider_cfg["base_url"],
        model=provider_cfg["model"],
        temperature=0.1,
        max_tokens=4096,
        http_async_client=http_async_client,
    )


# ---------------------------------------------------------------------------
# JSON Extraction Helper
# ---------------------------------------------------------------------------

def _extract_json(text: str) -> Optional[Dict]:
    """Extract JSON from LLM response, handling markdown code blocks and malformed output."""
    text = text.strip()
    
    # Strategy 1: Extract from markdown code block
    match = re.search(r'```(?:json)?\s*\n?(.*?)```', text, re.DOTALL)
    if match:
        candidate = match.group(1).strip()
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
    
    # Strategy 2: Find outermost JSON object by bracket counting (most reliable)
    start = text.find('{')
    if start != -1:
        depth = 0
        end = start
        for i, ch in enumerate(text[start:], start):
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    end = i
                    break
        if depth == 0:
            try:
                return json.loads(text[start:end+1])
            except json.JSONDecodeError:
                pass
    
    # Strategy 3: Simple greedy regex as last resort
    match = re.search(r'(\{.*\})', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    
    return None


def _normalize_plan(raw: Dict) -> QueryPlan:
    """Normalize raw dict to QueryPlan, handling alias variations."""
    steps = []
    for s in raw.get("steps", []):
        step_type = s.get("type") or s.get("query_type") or "events"
        steps.append(QueryStep(type=step_type, params=s.get("params", {})))
    
    return QueryPlan(
        intent=raw.get("intent", "unknown"),
        thinking=raw.get("thinking"),
        time_range=raw.get("time_range"),
        steps=steps,
        visualizations=raw.get("visualizations", ["event_table", "report"]),
        report_prompt=raw.get("report_prompt"),
        notice=raw.get("notice"),
    )


# ---------------------------------------------------------------------------
# Local Ollama Router (qwen2.5:3b)
# ---------------------------------------------------------------------------

class OllamaRouter:
    """Fast local intent router using qwen2.5:3b via Ollama.
    
    Routes queries to one of three categories:
    - rule_base: Simple lookups with explicit filters (time, location, event type, ID)
    - llm_tools: Complex queries requiring reasoning/comparison/synthesis
    - off_topic: Greetings, small talk, unrelated questions
    
    Tries multiple URLs in order (env var → host.docker.internal → localhost)
    to support both Docker and native environments.
    """

    MODEL = "qwen2.5:3b"

    def _get_urls(self) -> list[str]:
        """Return candidate Ollama URLs to try."""
        urls = []
        env_url = os.getenv("OLLAMA_URL")
        if env_url:
            urls.append(env_url)
        # Docker Desktop / host network
        urls.append("http://host.docker.internal:11434/api/generate")
        # Native / Linux Docker with host network
        urls.append("http://localhost:11434/api/generate")
        return urls

    SYSTEM_PROMPT = """You extract structured information from natural language queries for a GDELT event search system.

Extract and return ONLY this JSON format:
{
  "location": "canonical location name or null",
  "date_start": "YYYY-MM-DD or null",
  "date_end": "YYYY-MM-DD or null",
  "event_type": "protest|conflict|cooperation or null",
  "query_text": "free text search terms or null",
  "intent_category": "search|detail|brief|overview|hot|off_topic"
}

Date extraction rules:
- "May 1 2024" → "2024-05-01" to "2024-05-01"
- "Jan 2024" → "2024-01-01" to "2024-01-31"
- "Q1 2024" → "2024-01-01" to "2024-03-31"
- "last week" → previous 7 days from today
- "recently" → last 30 days
- "2024" → "2024-01-01" to "2024-12-31"
- null → "2024-01-01" to "2024-12-31"

Location canonicalization:
- "NYC", "NY", "New York City" → "New York"
- "DC", "Washington DC", "Washington, D.C." → "Washington DC"
- "LA" → "Los Angeles"
- "SF" → "San Francisco"
- "TX" → "Texas"

Event type mapping:
- "protest", "demonstration", "rally", "march" → "protest"
- "conflict", "war", "attack", "fight", "battle", "clash" → "conflict"
- "cooperation", "treaty", "agreement", "partnership" → "cooperation"

Intent categories:
- "search": general event search (most common)
- "detail": user provided event ID like EVT-2024-01-15-12345 — WHEN INPUT IS AN EVENT ID: set ONLY intent_category="detail" and query_text="the full EVT-... ID", ALL OTHER FIELDS MUST BE null
- "brief": "daily brief", "what happened on [date]"
- "overview": "situation in [region]", "what's happening in [region]"
- "hot": "hottest event", "top events", "most popular"
- "off_topic": greeting, thanks, small talk

All data is from 2024 only.
No other text. Just the JSON."""

    def __init__(self):
        self._client: Optional[httpx.AsyncClient] = None
        # Compile fallback patterns once
        self._EVENT_ID_PATTERN = re.compile(
            r'^(EVT-\d{4}-\d{2}-\d{2}-\d+)\b|'
            r'^(US-\d{8}-[A-Z]+-[A-Z]+-\d+)\b|'
            r'^\d{9,12}\b',
            re.IGNORECASE,
        )
        self._GREETING_PATTERNS = re.compile(
            r'^(hi|hello|hey|greetings|good morning|good afternoon|good evening|thanks|thank you|bye|goodbye|ok|okay)\b',
            re.IGNORECASE,
        )
        self._MONTH_YEAR_PATTERN = re.compile(
            r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})\b',
            re.IGNORECASE,
        )
        self._FULL_DATE_PATTERN = re.compile(
            r'\b(\d{4})[-/](\d{1,2})[-/](\d{1,2})\b|'
            r'\b(\d{1,2})[-/](\d{1,2})[-/](\d{4})\b|'
            r'\b(\d{4})(\d{2})(\d{2})\b',
        )
        self._LOCATION_PATTERN = re.compile(
            r'\b(?:in|at|near|around|on)\s+([A-Z][A-Za-z\s,]+?)(?=\s+(?:in|at|near|around|on|during|for|from|to|of|with|this|last|'
            r'\d{4}|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\?|$)|$)',
            re.IGNORECASE,
        )
        self._KNOWN_LOCATIONS = re.compile(
            r'\b(California|Texas|Florida|New York|Washington DC|Washington|Illinois|Pennsylvania|Ohio|'
            r'Georgia|North Carolina|Virginia|Michigan|Massachusetts|Arizona|Colorado|Minnesota|Wisconsin|'
            r'Maryland|Missouri|Tennessee|Indiana|Nevada|Oregon|Utah|Louisiana|Alabama|Kentucky|'
            r'Connecticut|Oklahoma|Iowa|Arkansas|Mississippi|Kansas|New Mexico|Nebraska|'
            r'West Virginia|Idaho|Hawaii|New Hampshire|Maine|Montana|Rhode Island|Delaware|'
            r'South Dakota|North Dakota|Alaska|Vermont|Wyoming|DC|'
            r'Los Angeles|Chicago|Houston|San Francisco|Seattle|Boston|Miami|Dallas|Philadelphia|'
            r'Atlanta|Denver|Phoenix|Detroit|Nashville|Portland|San Diego|Austin|New Orleans|'
            r'Las Vegas|Memphis|Louisville|Buffalo|Baltimore|Milwaukee|Tampa|Orlando|'
            r'Sacramento|Long Beach|Oakland|Canada|Mexico|United States|USA|US|'
            r'Ukraine|Gaza|Israel|China|Russia|UK|France|Germany|Japan|India|Australia|Brazil|'
            r'Europe|Asia|Africa|Middle East)\b',
            re.IGNORECASE,
        )
        self._MONTH_MAP = {
            'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'may': '05', 'jun': '06',
            'jul': '07', 'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12',
        }

    @property
    def client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=httpx.Timeout(10.0, connect=2.0))
        return self._client

    async def extract_context(self, query: str) -> QueryContext:
        """Extract structured context from natural language query.
        Tries each Ollama URL in order. Falls back to regex-based extraction on total failure.
        """
        prompt = f"{self.SYSTEM_PROMPT}\n\nQuery: \"{query}\"\n\nJSON:"
        last_error = None
        
        for url in self._get_urls():
            try:
                resp = await self.client.post(
                    url,
                    json={
                        "model": self.MODEL,
                        "prompt": prompt,
                        "stream": False,
                        "options": {"temperature": 0.0, "num_predict": 120},
                    },
                )
                resp.raise_for_status()
                data = resp.json()
                text = data.get("response", "").strip()
                
                raw = _extract_json(text)
                if raw is None:
                    continue
                
                location = raw.get("location")
                if location and location.lower() in ('null', 'none', 'n/a', ''):
                    location = None
                
                event_type = raw.get("event_type")
                if event_type and event_type.lower() in ('null', 'none', 'n/a', ''):
                    event_type = None
                
                query_text = raw.get("query_text")
                if query_text and query_text.lower() in ('null', 'none', 'n/a', ''):
                    query_text = None
                
                date_start = raw.get("date_start")
                date_end = raw.get("date_end")
                if date_start and date_start.lower() in ('null', 'none', 'n/a', ''):
                    date_start = None
                if date_end and date_end.lower() in ('null', 'none', 'n/a', ''):
                    date_end = None
                
                intent = raw.get("intent_category", "search")
                if intent not in ("search", "detail", "brief", "overview", "hot", "off_topic"):
                    intent = "search"
                
                # Post-process: if query_text looks like an event fingerprint, force intent=detail
                # and clear all other fields (fingerprint lookup does not need date/location filters)
                check_text = (query_text or "").strip()
                if not check_text:
                    check_text = user_input.strip()
                if check_text:
                    # Match EVT-YYYY-MM-DD-NNNNNNNNNN, US-YYYYMMDD-LOC-TYPE-NUM, or raw numeric ID
                    if re.match(r'^(EVT-\d{4}-\d{2}-\d{2}-\d+|US-\d{8}-[A-Z]+-[A-Z]+-\d+|\d{9,12})$', check_text, re.IGNORECASE):
                        intent = "detail"
                        location = None
                        date_start = None
                        date_end = None
                        event_type = None
                        # Put the fingerprint into query_text so planner can extract it
                        if not query_text:
                            query_text = check_text
                
                return QueryContext(
                    location=location,
                    date_start=date_start,
                    date_end=date_end,
                    event_type=event_type,
                    query_text=query_text,
                    intent_category=intent,
                    confidence="high",
                )
                
            except Exception as e:
                last_error = e
                continue
        
        print(f"[OllamaRouter] All URLs failed (last: {last_error}), falling back to regex extraction", flush=True)
        return self._fallback_extract_context(query)

    def _fallback_extract_context(self, query: str) -> QueryContext:
        """Regex-based fallback extraction when Ollama router fails."""
        q = query.lower().strip()
        
        # Greeting check
        if len(q) < 3 or self._GREETING_PATTERNS.match(q):
            return QueryContext(intent_category="off_topic", confidence="low")
        
        # Event ID check
        evt_match = self._EVENT_ID_PATTERN.search(query.strip())
        if evt_match:
            return QueryContext(intent_category="detail", confidence="low")
        
        # Location
        location = None
        loc_match = self._LOCATION_PATTERN.search(query)
        if loc_match:
            location = loc_match.group(1).strip()
        else:
            loc_fallback = self._KNOWN_LOCATIONS.search(query)
            location = loc_fallback.group(1) if loc_fallback else None
        if location:
            location = re.sub(r'\s+(in|at|near|around|on|during|for|from|to|of|with)$', '', location, flags=re.IGNORECASE).strip()
            if location.lower() in ('dc', 'washington dc', 'washington, dc'):
                location = 'Washington DC'
        
        # Date range
        start_date, end_date = None, None
        nat_match = self._NATURAL_DATE_PATTERN.search(query) if hasattr(self, '_NATURAL_DATE_PATTERN') else None
        if nat_match:
            if nat_match.group(1):
                month_abbr = nat_match.group(1).lower()[:3]
                d = nat_match.group(2).zfill(2)
                y = nat_match.group(3)
                start_date = f"{y}-{self._MONTH_MAP.get(month_abbr, '01')}-{d}"
                end_date = start_date
            elif nat_match.group(4):
                d = nat_match.group(4).zfill(2)
                month_abbr = nat_match.group(5).lower()[:3]
                y = nat_match.group(6)
                start_date = f"{y}-{self._MONTH_MAP.get(month_abbr, '01')}-{d}"
                end_date = start_date
        
        if not start_date:
            full_match = self._FULL_DATE_PATTERN.search(query)
            if full_match:
                if full_match.group(1):
                    start_date = f"{full_match.group(1)}-{full_match.group(2).zfill(2)}-{full_match.group(3).zfill(2)}"
                    end_date = start_date
                elif full_match.group(4):
                    start_date = f"{full_match.group(6)}-{full_match.group(4).zfill(2)}-{full_match.group(5).zfill(2)}"
                    end_date = start_date
                elif full_match.group(7):
                    start_date = f"{full_match.group(7)}-{full_match.group(8)}-{full_match.group(9)}"
                    end_date = start_date
        
        if not start_date:
            my_match = self._MONTH_YEAR_PATTERN.search(query)
            if my_match:
                month_abbr = my_match.group(1).lower()[:3]
                y = my_match.group(2)
                m = self._MONTH_MAP.get(month_abbr, '01')
                start_date = f"{y}-{m}-01"
                end_date = f"{y}-{m}-31"
        
        # Event type
        event_type = None
        if 'protest' in q or 'demonstration' in q or 'rally' in q or 'march' in q:
            event_type = 'protest'
        elif 'conflict' in q or 'war' in q or 'attack' in q or 'fight' in q or 'battle' in q or 'clash' in q:
            event_type = 'conflict'
        elif 'cooperation' in q or 'treaty' in q or 'agreement' in q or 'partnership' in q:
            event_type = 'cooperation'
        
        return QueryContext(
            intent_category="search",
            confidence="low",
            location=location,
            date_start=start_date,
            date_end=end_date,
            event_type=event_type,
            query_text=query.strip(),
        )

    async def extract_context_fast(self, query: str) -> QueryContext:
        """Fast-path context extraction using regex only — no Ollama call.
        
        Used for queries with obvious structured filters (date, location, event_type)
        where we don't need LLM reasoning. Returns in < 5ms vs 2s for Ollama.
        """
        import time
        t0 = time.time()
        
        q_lower = query.lower()
        
        # Date extraction
        date_start, date_end = None, None
        
        # Full date: "Jan 25 2024", "January 25, 2024", "2024-01-25"
        m = re.search(r'(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+(\d{1,2})(?:st|nd|rd|th)?[,\s]+(2024)', q_lower)
        if m:
            month_map = {'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,
                         'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12}
            month_abbr = q_lower[m.start():m.start()+3]
            month = month_map.get(month_abbr, 1)
            day = int(m.group(1))
            date_start = date_end = f"2024-{month:02d}-{day:02d}"
        else:
            m = re.search(r'(\d{4})-(\d{2})-(\d{2})', query)
            if m:
                date_start = date_end = m.group(0)
        
        # Month only: "feb 2024", "in february"
        if not date_start:
            m = re.search(r'(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*', q_lower)
            if m:
                month_map = {'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,
                             'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12}
                month_abbr = q_lower[m.start():m.start()+3]
                month = month_map.get(month_abbr, 1)
                date_start = f"2024-{month:02d}-01"
                date_end = f"2024-{month:02d}-28"  # Simple, data is Jan-only mostly
        
        # Location extraction
        location = None
        loc_patterns = [
            (r'(?:near|in|around)\s+(?:the\s+)?white\s+house', 'Washington DC'),
            (r'(?:near|in|around)\s+(?:washington\s+dc?|washington,\s*d\.?c\.?)', 'Washington DC'),
            (r'(?:near|in|around)\s+(?:new\s+york\s+city?|nyc|new\s+york)', 'New York'),
            (r'(?:near|in|around)\s+(?:los\s+angeles|la)', 'Los Angeles'),
            (r'(?:near|in|around)\s+(?:san\s+francisco|sf)', 'San Francisco'),
            (r'(?:near|in|around)\s+texas', 'Texas'),
            (r'(?:near|in|around)\s+california', 'California'),
            (r'(?:near|in|around)\s+florida', 'Florida'),
        ]
        for pattern, canonical in loc_patterns:
            if re.search(pattern, q_lower):
                location = canonical
                break
        
        # Event type extraction
        event_type = None
        if 'protest' in q_lower or 'demonstration' in q_lower or 'rally' in q_lower:
            event_type = 'protest'
        elif 'conflict' in q_lower or 'war' in q_lower or 'attack' in q_lower:
            event_type = 'conflict'
        elif 'cooperation' in q_lower or 'treaty' in q_lower or 'agreement' in q_lower:
            event_type = 'cooperation'
        
        # Intent: brief if "what happened", otherwise search
        intent = 'search'
        if re.search(r'what\s+happened|daily\s+brief|what\s+was', q_lower):
            intent = 'brief'
        
        # Query text: strip out obvious filter words to keep only meaningful search terms
        query_text = query
        
        elapsed_ms = round((time.time() - t0) * 1000, 3)
        print(f"[OllamaRouter] Fast-path regex extraction: {elapsed_ms}ms | loc={location}, date={date_start}, type={event_type}, intent={intent}", flush=True)
        
        return QueryContext(
            location=location,
            date_start=date_start,
            date_end=date_end,
            event_type=event_type,
            query_text=query_text,
            intent_category=intent,
            confidence="high",
        )

    async def close(self):
        if self._client:
            await self._client.aclose()
            self._client = None


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------

PLANNER_SYSTEM_PROMPT = """You are GDELT Event Search AI. Your job is to find specific events and incidents. Output ONLY raw JSON.

JSON schema:
{
  "thinking": "1-sentence reasoning",
  "intent": "short description",
  "time_range": {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"} or null,
  "steps": [{"type": "QUERY_TYPE", "params": {...}}],
  "visualizations": ["event_table", "report"],
  "report_prompt": "prompt for AI analysis"
}

Available tools (event search only):
- events: {query, start_date, end_date, location_hint, event_type, actor, limit} — broad event search
- event_detail: {fingerprint} — specific event by EVT-ID
- similar_events: {seed_event_id} — find events similar to a given event (pair with event_detail)
- hot_events: {query_date, top_n} — hottest single-day events
- top_events: {start_date, end_date, region_filter, event_type, top_n} — top events across a time range
- daily_brief: {query_date} — daily summary of key events
- regional_overview: {start_date, end_date, region} — situation summary for a specific region

Date rules:
- "last month" = previous calendar month
- "this week" = current Mon-Sun
- "recently" or no time = last 30 days
- "Feb 2024" = 2024-02-01 to 2024-02-29
- "Q3 2024" = 2024-07-01 to 2024-09-30
- All data is 2024 only.

Off-topic → {"intent": "off_topic", "steps": [], "visualizations": []}

Rules:
- thinking: 1 sentence max.
- Max 2 steps.
- You do NOT do data analysis, trends, dashboards, or maps — those are handled by the Dashboard tab.
- Always include "report" in visualizations."""


class Planner:
    """Hybrid planner: local Ollama router → rule-based fast path OR remote LLM tool execution."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self._llm_config = config
        self._llm: Optional[ChatOpenAI] = None
        self.router = OllamaRouter()

    @property
    def llm(self) -> ChatOpenAI:
        if self._llm is None:
            self._llm = build_llm(self._llm_config)
        return self._llm

    # Quick off-topic / greeting detection without LLM
    _GREETING_PATTERNS = re.compile(
        r'^(hi+|hello|hey|thanks?|thank you|ok+|bye|goodbye|see you|[?]+)\s*$',
        re.IGNORECASE
    )

    # Detect if user explicitly mentions a time range
    _TIME_MENTIONED = re.compile(
        r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b|'
        r'\b\d{4}\b|'
        r'\b(this|last|past)\s+(week|month|year|day)\b|'
        r'\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b|'
        r'\byesterday\b|\btoday\b',
        re.IGNORECASE,
    )

    # Extract location from "... in/at/near/around/on <place>"
    # Terminates at next preposition, time word, or end of string
    _LOCATION_PATTERN = re.compile(
        r'\b(?:in|at|near|around|on)\s+([A-Z][A-Za-z\s,]+?)(?=\s+(?:in|at|near|around|on|during|for|from|to|of|with|this|last|'
        r'\d{4}|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\?|$)|$)',
        re.IGNORECASE,
    )

    # Known locations for direct word-boundary matching (no "in" prefix needed)
    _KNOWN_LOCATIONS = re.compile(
        r'\b(California|Texas|Florida|New York|Washington DC|Washington|Illinois|Pennsylvania|Ohio|'
        r'Georgia|North Carolina|Virginia|Michigan|Massachusetts|Arizona|Colorado|Minnesota|Wisconsin|'
        r'Maryland|Missouri|Tennessee|Indiana|Nevada|Oregon|Utah|Louisiana|Alabama|Kentucky|'
        r'Connecticut|Oklahoma|Iowa|Arkansas|Mississippi|Kansas|New Mexico|Nebraska|'
        r'West Virginia|Idaho|Hawaii|New Hampshire|Maine|Montana|Rhode Island|Delaware|'
        r'South Dakota|North Dakota|Alaska|Vermont|Wyoming|DC|'
        r'Los Angeles|Chicago|Houston|San Francisco|Seattle|Boston|Miami|Dallas|Philadelphia|'
        r'Atlanta|Denver|Phoenix|Detroit|Nashville|Portland|San Diego|Austin|New Orleans|'
        r'Las Vegas|Memphis|Louisville|Buffalo|Baltimore|Milwaukee|Tampa|Orlando|'
        r'Sacramento|Long Beach|Oakland|Canada|Mexico|United States|USA|US|'
        r'Ukraine|Gaza|Israel|China|Russia|UK|France|Germany|Japan|India|Australia|Brazil|'
        r'Europe|Asia|Africa|Middle East)\b',
        re.IGNORECASE,
    )

    # Hot / top events keywords (used by fallback extraction only)
    _HOT_KEYWORDS = re.compile(
        r'\b(hottest|hot|top(?:\s+\d+)?(?:\s+(?:events?|news?|stories?))?|most\s+(?:popular|reported|mentioned|important)|trending)\b',
        re.IGNORECASE,
    )

    # Detect specific event ID patterns (EVT-..., US-YYYYMMDD-LOC-TYPE-NUM, or raw numeric ID)
    _EVENT_ID_PATTERN = re.compile(
        r'^(EVT-\d{4}-\d{2}-\d{2}-\d+)\b|'
        r'^(US-\d{8}-[A-Z]+-[A-Z]+-\d+)\b|'
        r'^\d{9,12}\b',
        re.IGNORECASE,
    )

    # Parse month+year like "march 2024" or "feb 2024" (fallback only)
    _MONTH_YEAR_PATTERN = re.compile(
        r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})\b',
        re.IGNORECASE,
    )
    _MONTH_MAP = {
        'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'may': '05', 'jun': '06',
        'jul': '07', 'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12',
    }

    # Parse full numeric dates: 2024-10-15, 10/15/2024, 20241015 (fallback only)
    _FULL_DATE_PATTERN = re.compile(
        r'\b(\d{4})[-/](\d{1,2})[-/](\d{1,2})\b|'
        r'\b(\d{1,2})[-/](\d{1,2})[-/](\d{4})\b|'
        r'\b(\d{4})(\d{2})(\d{2})\b',
    )

    # Parse natural language dates: "May 1 2024", "1 May 2024" (fallback only)
    _NATURAL_DATE_PATTERN = re.compile(
        r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{1,2})(?:st|nd|rd|th)?,?\s+(\d{4})\b|'
        r'\b(\d{1,2})(?:st|nd|rd|th)?\s+(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})\b',
        re.IGNORECASE,
    )

    # Location extraction (fallback only)
    _LOCATION_PATTERN = re.compile(
        r'\b(?:in|at|near|around|on)\s+([A-Z][A-Za-z\s,]+?)(?=\s+(?:in|at|near|around|on|during|for|from|to|of|with|this|last|'
        r'\d{4}|(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*|\?|$)|$)',
        re.IGNORECASE,
    )

    _KNOWN_LOCATIONS = re.compile(
        r'\b(California|Texas|Florida|New York|Washington DC|Washington|Illinois|Pennsylvania|Ohio|'
        r'Georgia|North Carolina|Virginia|Michigan|Massachusetts|Arizona|Colorado|Minnesota|Wisconsin|'
        r'Maryland|Missouri|Tennessee|Indiana|Nevada|Oregon|Utah|Louisiana|Alabama|Kentucky|'
        r'Connecticut|Oklahoma|Iowa|Arkansas|Mississippi|Kansas|New Mexico|Nebraska|'
        r'West Virginia|Idaho|Hawaii|New Hampshire|Maine|Montana|Rhode Island|Delaware|'
        r'South Dakota|North Dakota|Alaska|Vermont|Wyoming|DC|'
        r'Los Angeles|Chicago|Houston|San Francisco|Seattle|Boston|Miami|Dallas|Philadelphia|'
        r'Atlanta|Denver|Phoenix|Detroit|Nashville|Portland|San Diego|Austin|New Orleans|'
        r'Las Vegas|Memphis|Louisville|Buffalo|Baltimore|Milwaukee|Tampa|Orlando|'
        r'Sacramento|Long Beach|Oakland|Canada|Mexico|United States|USA|US|'
        r'Ukraine|Gaza|Israel|China|Russia|UK|France|Germany|Japan|India|Australia|Brazil|'
        r'Europe|Asia|Africa|Middle East)\b',
        re.IGNORECASE,
    )

    # -----------------------------------------------------------------------
    # Fallback Entity Extraction (when Ollama is unavailable)
    # -----------------------------------------------------------------------

    # (Moved to OllamaRouter class above)

    # -----------------------------------------------------------------------
    # Rule-Based Planner (uses structured context from router)
    # -----------------------------------------------------------------------

    def _rule_based_plan(self, ctx: QueryContext) -> Optional[QueryPlan]:
        """Fast rule-based planner using structured context from Ollama router."""
        # Off-topic
        if ctx.intent_category == "off_topic":
            return QueryPlan(
                intent="off_topic",
                thinking="User input is a greeting or too short — no tools needed.",
                steps=[],
                visualizations=[],
                report_prompt=None,
            )

        # Event detail lookup
        if ctx.intent_category == "detail":
            # Try user_input first, then query_text (Ollama may put fingerprint there)
            search_text = (ctx.user_input or "") + " " + (ctx.query_text or "")
            evt_match = self._EVENT_ID_PATTERN.search(search_text)
            if evt_match:
                fingerprint = evt_match.group(1) or evt_match.group(2) or evt_match.group(0)
                # For EVT-IDs, extract numeric seed for similar_events
                if fingerprint.upper().startswith('EVT-'):
                    try:
                        seed_id = int(fingerprint.split('-')[-1])
                    except ValueError:
                        seed_id = None
                elif fingerprint.upper().startswith('US-'):
                    # Custom fingerprint: look up by fingerprint string, no similar_events seed
                    seed_id = None
                else:
                    seed_id = int(fingerprint)
                steps = [QueryStep(type="event_detail", params={"fingerprint": fingerprint})]
                if seed_id:
                    steps.append(QueryStep(type="similar_events", params={"seed_event_id": seed_id, "limit": 10}))
                return QueryPlan(
                    intent="event_detail_lookup",
                    thinking="User provided a specific event ID — retrieving event details + similar events.",
                    steps=steps,
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize this specific GDELT event ({fingerprint}) and highlight related events.",
                )

        # Daily brief
        if ctx.intent_category == "brief":
            query_date = ctx.date_start or (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
            end_date = ctx.date_end or query_date

            # If location is provided, search events in that location instead of global daily stats
            if ctx.location:
                params: Dict[str, Any] = {
                    "limit": 20,
                    "start_date": query_date,
                    "end_date": end_date,
                    "location_hint": ctx.location,
                }
                if ctx.event_type:
                    params["event_type"] = ctx.event_type
                return QueryPlan(
                    intent=f"events_{ctx.location}_{query_date}",
                    thinking=f"User requested events in {ctx.location} on {query_date}. Searching for location-matched events.",
                    steps=[QueryStep(type="events", params=params)],
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize what happened in {ctx.location} on {query_date}.",
                )

            # No location — return global daily summary
            return QueryPlan(
                intent="daily_brief",
                thinking=f"User requested daily brief for {query_date}.",
                steps=[QueryStep(type="daily_brief", params={"query_date": query_date})],
                visualizations=["stats_cards", "report"],
                report_prompt=f"Summarize the key events on {query_date}.",
            )

        # Hot / Top events
        if ctx.intent_category == "hot":
            is_single_day = ctx.date_start is not None and ctx.date_end is not None and ctx.date_start == ctx.date_end
            if is_single_day:
                params = {"query_date": ctx.date_start, "top_n": 10}
                if ctx.location:
                    params["region_filter"] = ctx.location
                return QueryPlan(
                    intent=f"hot_events_{ctx.location or 'global'}",
                    thinking=f"User requested hot events for {ctx.date_start}." + (f" Filtering by region: {ctx.location}." if ctx.location else ""),
                    steps=[QueryStep(type="hot_events", params=params)],
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize the hottest events on {ctx.date_start}" + (f" in {ctx.location}" if ctx.location else "") + ".",
                )
            else:
                params = {
                    "start_date": ctx.date_start or DEFAULT_DATA_START,
                    "end_date": ctx.date_end or DEFAULT_DATA_END,
                    "top_n": 10,
                }
                if ctx.location:
                    params["region_filter"] = ctx.location
                if ctx.event_type:
                    params["event_type"] = ctx.event_type
                return QueryPlan(
                    intent=f"top_events_{ctx.event_type or 'all'}_{ctx.location or 'global'}",
                    thinking=f"User requested top events" + (f" ({ctx.event_type})" if ctx.event_type else "") + (f" in {ctx.location}" if ctx.location else "") + f" from {params['start_date']} to {params['end_date']}.",
                    steps=[QueryStep(type="top_events", params=params)],
                    visualizations=["event_table", "report"],
                    report_prompt=f"Summarize the top {ctx.event_type or ''} events" + (f" in {ctx.location}" if ctx.location else "") + f" from {params['start_date']} to {params['end_date']}.",
                )

        # Regional overview
        if ctx.intent_category == "overview" and ctx.location:
            params = {"region": ctx.location}
            if ctx.date_start and ctx.date_end:
                params["start_date"] = ctx.date_start
                params["end_date"] = ctx.date_end
            else:
                params["time_range"] = "week"
            return QueryPlan(
                intent=f"regional_overview_{ctx.location}",
                thinking=f"User requested regional overview for {ctx.location}." + (f" Time range: {ctx.date_start} to {ctx.date_end}." if ctx.date_start else " Default: last week."),
                steps=[QueryStep(type="regional_overview", params=params)],
                visualizations=["stats_cards", "event_table", "report"],
                report_prompt=f"Provide a situation overview for {ctx.location}" + (f" from {ctx.date_start} to {ctx.date_end}" if ctx.date_start else " over the last week") + ".",
            )

        # Default: events search
        params: Dict[str, Any] = {
            "limit": 50,
            "start_date": ctx.date_start or DEFAULT_DATA_START,
            "end_date": ctx.date_end or DEFAULT_DATA_END,
        }
        if ctx.location:
            params["location_hint"] = ctx.location
        if ctx.event_type:
            params["event_type"] = ctx.event_type
        if ctx.query_text:
            params["query"] = ctx.query_text
        
        intent_name = f"events_{ctx.event_type or 'all'}_{ctx.location or 'global'}"
        return QueryPlan(
            intent=intent_name,
            thinking="Event search based on extracted location, date, and event type.",
            steps=[QueryStep(type="events", params=params)],
            visualizations=["event_table", "report"],
            report_prompt=f"Summarize {ctx.event_type or 'events'} {f'in {ctx.location}' if ctx.location else ''} from {params['start_date']} to {params['end_date']}.",
        )

    # -----------------------------------------------------------------------
    # LLM Tool Planner
    # -----------------------------------------------------------------------

    async def _llm_plan(self, query: str, ctx: QueryContext) -> QueryPlan:
        """Use remote LLM for complex queries. Passes simplified context extracted by Ollama."""
        # Build simplified user intent from structured context
        parts = []
        if ctx.location:
            parts.append(f"Location: {ctx.location}")
        if ctx.date_start:
            if ctx.date_start == ctx.date_end:
                parts.append(f"Date: {ctx.date_start}")
            else:
                parts.append(f"Date range: {ctx.date_start} to {ctx.date_end}")
        if ctx.event_type:
            parts.append(f"Event type: {ctx.event_type}")
        if ctx.query_text:
            parts.append(f"Search terms: {ctx.query_text}")
        
        simplified = "; ".join(parts) if parts else query
        
        # Also attach original query as reference
        user_msg = f"Simplified user intent: {simplified}\n\nOriginal request: \"{query}\""
        
        # Add any extra context from Ollama
        context_parts = []
        if ctx.intent_category != "search":
            context_parts.append(f"Intent category: {ctx.intent_category}")
        context_str = "\n".join(context_parts) if context_parts else ""
        if context_str:
            user_msg += f"\n\nExtracted context:\n{context_str}"
        user_msg += "\n\nRespond with ONLY raw JSON:"

        messages = [
            SystemMessage(content=PLANNER_SYSTEM_PROMPT),
            HumanMessage(content=user_msg),
        ]

        try:
            response = await asyncio.wait_for(self.llm.ainvoke(messages), timeout=120.0)
            content = response.content if hasattr(response, "content") else str(response)
            print(f"[Planner] raw response length: {len(content)}", flush=True)

            raw = _extract_json(content)
            if raw is None:
                # Print full response for debugging (truncated if very long)
                debug_content = content if len(content) < 800 else content[:400] + "\n... [truncated]\n" + content[-200:]
                print(f"[Planner] JSON extraction failed. Raw response:\n{debug_content}", flush=True)
                raise ValueError("Could not extract valid JSON from LLM response")

            plan = _normalize_plan(raw)
            print(f"[Planner] generated plan: {plan.intent} with {len(plan.steps)} steps", flush=True)
            return plan

        except asyncio.TimeoutError:
            print(f"[Planner] LLM timeout after 120s, using fallback plan", flush=True)
            return self._fallback_plan(query)
        except Exception as e:
            print(f"[Planner] failed: {e}, using fallback plan", flush=True)
            return self._fallback_plan(query)

    def _fallback_plan(self, query: str) -> QueryPlan:
        """Fallback when LLM or router fails."""
        return QueryPlan(
            intent="fallback_search",
            thinking="Planner error. Falling back to top events search.",
            steps=[QueryStep(type="top_events", params={"top_n": 20, "start_date": DEFAULT_DATA_START, "end_date": DEFAULT_DATA_END})],
            visualizations=["event_table", "report"],
            report_prompt=f"Top events for: {query}",
            notice="Planner error. Showing top-ranked events across the full dataset (fast mode). Add a month or date for more precise results.",
        )

    # -----------------------------------------------------------------------
    # Main Entry Point
    # -----------------------------------------------------------------------

    async def plan(self, user_query: str) -> tuple[QueryPlan, List[Dict[str, Any]]]:
        """Generate a query plan from user input.
        
        Simple flow:
        1. Ollama extracts structured context (location, date, event_type, intent).
        2. Rule-based planner directly maps context to tool calls.
        3. Only truly ambiguous queries fall back to remote LLM.
        Returns (QueryPlan, phases).
        """
        import time
        phases: List[Dict[str, Any]] = []
        stripped = user_query.strip()

        # Fast path: greetings (avoid even calling router)
        if self._GREETING_PATTERNS.match(stripped) or len(stripped) < 3:
            print(f"[Planner] Fast off-topic detected for: '{stripped}'", flush=True)
            return QueryPlan(
                intent="off_topic",
                steps=[],
                visualizations=[],
                report_prompt=None,
            ), [{"name": "Intent Check", "status": "completed", "detail": "Greeting or too-short input detected — skipping AI.", "elapsed_ms": 0}]

        # Phase 1: Context Extraction (Ollama)
        t0 = time.time()
        ctx = await self.router.extract_context(stripped)
        ctx.user_input = stripped  # Preserve original query
        t_router = round((time.time() - t0) * 1000, 1)
        
        detail_parts = [f"intent='{ctx.intent_category}'"]
        if ctx.location:
            detail_parts.append(f"loc='{ctx.location}'")
        if ctx.date_start:
            detail_parts.append(f"date={ctx.date_start} to {ctx.date_end}")
        if ctx.event_type:
            detail_parts.append(f"type='{ctx.event_type}'")
        if ctx.query_text:
            detail_parts.append(f"text='{ctx.query_text}'")
        
        print(f"[Planner] Context: {', '.join(detail_parts)} | confidence={ctx.confidence} in {t_router}ms", flush=True)
        phases.append({
            "name": "Context Extraction",
            "status": "completed",
            "detail": f"Local Qwen2.5b extracted: {', '.join(detail_parts)} ({ctx.confidence} confidence)",
            "elapsed_ms": t_router,
        })

        if ctx.intent_category == "off_topic":
            return QueryPlan(
                intent="off_topic",
                steps=[],
                visualizations=[],
                report_prompt=None,
            ), phases

        # Phase 2: Rule-Based Plan Generation — direct tool mapping, no LLM for simple queries
        t0 = time.time()
        fast_plan = self._rule_based_plan(ctx)
        if fast_plan:
            t_plan = round((time.time() - t0) * 1000, 1)
            step_types = ' → '.join(s.type for s in fast_plan.steps)
            detail = f"Matched '{fast_plan.intent}' | Tools: {step_types}"
            print(f"[Planner] Rule-based plan: {fast_plan.intent} with {len(fast_plan.steps)} steps in {t_plan}ms", flush=True)
            phases.append({"name": "Rule-Based Planning", "status": "completed", "detail": detail, "elapsed_ms": t_plan})
            return fast_plan, phases
        
        # Fallback: remote LLM for truly ambiguous queries
        print(f"[Planner] Rule base couldn't match, falling back to remote LLM", flush=True)
        plan = await self._llm_plan(stripped, ctx)
        t_plan = round((time.time() - t0) * 1000, 1)
        step_types = ' → '.join(s.type for s in plan.steps)
        detail = f"Remote LLM generated plan | Tools: {step_types}"
        phases.append({"name": "AI Planning", "status": "completed", "detail": detail, "elapsed_ms": t_plan})
        return plan, phases


# ---------------------------------------------------------------------------
# Report Generator
# ---------------------------------------------------------------------------

REPORT_SYSTEM_PROMPT = """You are a GDELT event narrative analyst. Weave event data into a coherent story with a clear narrative arc.

Rules:
- Output plain text / markdown. Do NOT use JSON.
- 2-4 short paragraphs max.
- Tell a story: context → key events → implications or connections.
- Cite specific dates, locations, actors, and article counts from the data.
- If data is empty or sparse, say so directly.
- No preamble like "Here is the analysis". Start immediately with the story."""


class ReportGenerator:
    """Generates narrative reports from structured event data.
    
    Pre-processes raw step results into a clean narrative format before sending to LLM.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.llm = build_llm(config)

    def _get_response_text(self, response) -> str:
        """Extract text from LLM response, handling kimi k2 reasoning_content."""
        text = ""
        if hasattr(response, "content") and response.content:
            text = response.content.strip()
        if not text and hasattr(response, "additional_kwargs"):
            text = response.additional_kwargs.get("reasoning_content", "") or ""
            if text:
                text = text.strip()
        if not text and hasattr(response, "response_metadata"):
            text = response.response_metadata.get("reasoning_content", "") or ""
            if text:
                text = text.strip()
        return text

    @staticmethod
    def _format_event(evt: Dict[str, Any], is_primary: bool = False) -> str:
        """Format a single event into a concise narrative string."""
        parts = []
        prefix = "PRIMARY: " if is_primary else "- "
        
        # Date
        date = evt.get("SQLDATE") or evt.get("date", "unknown date")
        parts.append(f"Date: {date}")
        
        # Location
        loc = evt.get("ActionGeo_FullName") or evt.get("location_name") or evt.get("ActionGeo_CountryCode", "unknown")
        parts.append(f"Location: {loc}")
        
        # Actors
        actor1 = evt.get("Actor1Name") or evt.get("actor1_name", "")
        actor2 = evt.get("Actor2Name") or evt.get("actor2_name", "")
        if actor1 or actor2:
            actors = f"{actor1 or '?'} vs {actor2 or '?'}"
            parts.append(f"Actors: {actors}")
        
        # Headline / title
        headline = evt.get("headline")
        if not headline and (actor1 or actor2):
            headline = f"{actor1 or 'Unknown'} vs {actor2 or 'Unknown'}"
        if headline:
            parts.append(f"Title: {headline}")
        
        # Summary
        summary = evt.get("summary", "")
        if summary:
            summary = summary[:250] + "..." if len(summary) > 250 else summary
            parts.append(f"Summary: {summary}")
        
        # Articles (signal of importance)
        articles = evt.get("NumArticles") or evt.get("num_articles")
        if articles:
            parts.append(f"Articles: {articles}")
        
        # Goldstein scale (conflict/cooperation)
        goldstein = evt.get("GoldsteinScale") or evt.get("goldstein_scale")
        if goldstein is not None:
            tone = "conflict" if goldstein < -5 else "cooperation" if goldstein > 5 else "neutral"
            parts.append(f"Tone: {tone} ({goldstein})")
        
        # Event type label
        evt_type = evt.get("event_type_label") or evt.get("event_type")
        if evt_type:
            parts.append(f"Type: {evt_type}")
        
        return prefix + " | ".join(parts)

    def _format_data_for_report(self, data: Dict[str, Any]) -> str:
        """Pre-process raw step results into a clean narrative input."""
        sections = []
        total_events = 0
        
        for key, item in data.items():
            step_type = item.get("type", "unknown")
            step_data = item.get("data")
            
            if step_type == "event_detail" and step_data:
                sections.append("=== PRIMARY EVENT ===")
                if isinstance(step_data, dict):
                    sections.append(self._format_event(step_data, is_primary=True))
                    # Include raw event_data if available
                    raw = step_data.get("event_data")
                    if raw and isinstance(raw, dict):
                        sections.append(self._format_event(raw, is_primary=True))
                else:
                    sections.append(str(step_data))
                    
            elif step_type == "similar_events" and step_data:
                events = step_data if isinstance(step_data, list) else []
                sections.append(f"=== {len(events)} RELATED EVENTS ===")
                for evt in events[:8]:  # Cap at 8
                    sections.append(self._format_event(evt))
                    total_events += 1
                    
            elif step_type in ("events", "top_events", "hot_events") and step_data:
                events = step_data if isinstance(step_data, list) else []
                sections.append(f"=== {len(events)} EVENTS FOUND ===")
                for evt in events[:10]:  # Cap at 10
                    sections.append(self._format_event(evt))
                    total_events += 1
                    
            elif step_type == "regional_overview" and step_data:
                sections.append("=== REGIONAL SITUATION ===")
                if isinstance(step_data, dict):
                    summary = step_data.get("summary", {})
                    if summary:
                        sections.append(f"Summary: {json.dumps(summary, default=str)}")
                    hot = step_data.get("hot_events", [])
                    if hot:
                        sections.append(f"Hot events ({len(hot)}):")
                        for evt in hot[:5]:
                            sections.append(self._format_event(evt))
                else:
                    sections.append(str(step_data))
                    
            elif step_type == "daily_brief" and step_data:
                sections.append("=== DAILY BRIEF ===")
                if isinstance(step_data, dict):
                    total = step_data.get("total_events")
                    if total:
                        sections.append(f"Total events: {total}")
                    conflict = step_data.get("conflict_events")
                    if conflict is not None:
                        sections.append(f"Conflict events: {conflict}")
                    avg_tone = step_data.get("avg_tone")
                    if avg_tone is not None:
                        sections.append(f"Avg tone: {avg_tone}")
                else:
                    sections.append(str(step_data))
        
        result = "\n\n".join(sections)
        # Hard cap at ~5000 chars to stay within token budget
        if len(result) > 5000:
            result = result[:4800] + "\n\n... [additional events omitted]"
        return result

    async def generate(self, data: Dict[str, Any], prompt: Optional[str] = None) -> ReportResult:
        """Generate a narrative report from query results."""
        # Pre-process data into narrative format
        narrative_data = self._format_data_for_report(data)
        
        if not narrative_data.strip() or narrative_data.strip() == "=== 0 EVENTS FOUND ===":
            return ReportResult(
                summary="No events were found for this query. Try broadening your search (e.g., removing location filters or expanding the date range).",
                key_findings=[],
            )

        user_prompt = prompt or "Tell the story of these events. Connect them with context and implications."

        messages = [
            SystemMessage(content=REPORT_SYSTEM_PROMPT),
            HumanMessage(content=f"{user_prompt}\n\nEvent Data:\n{narrative_data}\n\nWrite the story:"),
        ]

        try:
            response = await asyncio.wait_for(self.llm.ainvoke(messages), timeout=120.0)
            text = self._get_response_text(response)

            # Clean up markdown code blocks if any
            text = re.sub(r'^```.*?\n', '', text, flags=re.DOTALL)
            text = re.sub(r'\n```$', '', text)

            if not text:
                return ReportResult(
                    summary="No report content was generated.",
                    key_findings=[],
                )

            # Split into summary + bullet findings
            lines = [l.strip() for l in text.split('\n') if l.strip()]
            summary_lines = []
            findings = []
            in_findings = False
            for line in lines:
                if line.lower().startswith(('key finding', 'findings', 'highlights', '- ')):
                    in_findings = True
                if in_findings and (line.startswith('- ') or line.startswith('* ')):
                    findings.append(line[2:].strip())
                elif in_findings:
                    findings.append(line)
                else:
                    summary_lines.append(line)

            summary = '\n'.join(summary_lines) if summary_lines else text
            if len(summary) > 4000:
                summary = summary[:4000] + "..."

            print(f"[ReportGenerator] Generated report: {len(summary)} chars summary, {len(findings)} findings", flush=True)
            return ReportResult(summary=summary, key_findings=findings)

        except asyncio.TimeoutError:
            print("[ReportGenerator] LLM timeout after 120s", flush=True)
            return ReportResult(
                summary="AI report generation timed out. The event data is still available above.",
                key_findings=[],
            )
        except Exception as e:
            print(f"[ReportGenerator] Failed: {e}", flush=True)
            return ReportResult(
                summary="Unable to generate AI report at this time. The analysis data is still available above.",
                key_findings=[],
            )
